import {StyleSheet, Dimensions} from 'react-native';

const height = Dimensions.get('window').height,
	width = Dimensions.get('window').width;

export default StyleSheet.create({
	container: {
		width: width,
		height: height,
	},
	backgroundImage: {
		width: width,
		height: height,
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		top: 0,
		opacity: 0.3,
	},
	authForm: {
		width: width,
		height: height,
		position: 'relative',
	},
	logo: {
		width: width * 0.5,
		maxWidth: 207,
		height: 160,
		marginLeft: 'auto',
		marginRight: 'auto',
		marginBottom: 24,
	},
	inputContainer: {
		position: 'relative',
		width: width,
		maxWidth: 360,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	input: {
		position: 'relative',
		zIndex: 1150,
		backgroundColor: '#ebebeb',
		color: 'black',
		marginBottom: 20,
		paddingVertical: 12,
		paddingHorizontal: 16,
		borderRadius: 5,
		fontSize: 16,
		overflow: 'hidden',
		width: width * 0.8,
		maxWidth: 332,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	forgotPasswordButton: {
		position: 'absolute',
		zIndex: 1250,
		top: 4.5,
		right: 18,
		backgroundColor: 'white',
		padding: 10,
		borderRadius: 4,
	},
	forgotPasswordText: {
		color: 'rgba(0,0,0,.5)',
		fontSize: 12,
		textAlign: 'right',
		marginBottom: 32,
	},
	forgotPasswordIcon: {
		color: '#333',
		fontSize: 12,
	},
	button: {
		paddingVertical: 14,
		paddingHorizontal: 26,
		flexDirection: 'row',
		flexWrap: 'nowrap',
		alignItems: 'center',
		alignContent: 'center',
		justifyContent: 'center',
		borderRadius: 8,
		marginTop: 24,
		width: width * 0.5,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	buttonText: {
		fontSize: 16,
		fontWeight: 'bold',
	},
	registerContainer: {
		marginTop: 20,
		flexDirection: 'row',
		justifyContent: 'center',
	},
	registerText: {
		marginRight: 8,
		color: '#333',
		fontSize: 14,
	},
	registerButtonText: {
		color: '#333',
		fontWeight: 'bold',
		fontSize: 14,
	},
	thirdPartySeparator: {
		width: width * 0.7,
		height: 2,
		maxWidth: 332,
		marginLeft: 'auto',
		marginRight: 'auto',
		backgroundColor: '#e6e6e6',
		marginTop: 36,
		marginBottom: 24,
	},
	thirdPartyText: {
		textAlign: 'center',
		fontSize: 16,
		marginTop: 16,
	},
	thirdPartyButtonContainer: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		width: width * 0.8,
		maxWidth: 332,
		marginLeft: 'auto',
		marginRight: 'auto',
	},
	thirdPartyButton: {
		flexDirection: 'row',
		flexWrap: 'nowrap',
		alignItems: 'center',
		justifyContent: 'center',
		margin: 8,
		flex: 1,
		paddingTop: 14,
		paddingBottom: 14,
		borderStyle: 'solid',
		borderRadius: 8,
		overflow: 'hidden',
	},
	buttonGradient: {
		position: 'absolute',
		top: 0,
		bottom: 0,
		left: 0,
		right: 0,
	},
	thirdPartyAuthIcon: {
		color: '#333',
		fontSize: 28,
	},
	modalInside:{
        backgroundColor:'white',
        padding:20,
        borderRadius:15
    },
});
